// Auto-generated by update-characters.js
// Last updated: 2026-01-16T21:39:24.426Z

const characterData = [
  {
    "id": "24921505",
    "name": "Mira Wa'neko",
    "world": "Diabolos [Crystal]",
    "image": "https://img2.finalfantasyxiv.com/f/7c13a0269a6d7953946aff5be6ecff69_7b33d33ae3ecb996f778a5f67a6a0af6fl0.jpg?1768586024",
    "jobs": {
      "combat": [
        {
          "name": "Gunbreaker",
          "level": 100,
          "abbr": "GNB"
        },
        {
          "name": "White Mage",
          "level": 100,
          "abbr": "WHM"
        },
        {
          "name": "Scholar",
          "level": 100,
          "abbr": "SCH"
        },
        {
          "name": "Astrologian",
          "level": 100,
          "abbr": "AST"
        },
        {
          "name": "Sage",
          "level": 100,
          "abbr": "SGE"
        },
        {
          "name": "Dragoon",
          "level": 100,
          "abbr": "DRG"
        },
        {
          "name": "Ninja",
          "level": 100,
          "abbr": "NIN"
        },
        {
          "name": "Reaper",
          "level": 100,
          "abbr": "RPR"
        },
        {
          "name": "Viper",
          "level": 100,
          "abbr": "VPR"
        },
        {
          "name": "Dancer",
          "level": 100,
          "abbr": "DNC"
        },
        {
          "name": "Summoner",
          "level": 100,
          "abbr": "SMN"
        },
        {
          "name": "Red Mage",
          "level": 100,
          "abbr": "RDM"
        },
        {
          "name": "Pictomancer",
          "level": 100,
          "abbr": "PCT"
        },
        {
          "name": "Black Mage",
          "level": 94,
          "abbr": "BLM"
        },
        {
          "name": "Bard",
          "level": 79,
          "abbr": "BRD"
        },
        {
          "name": "Blue Mage",
          "level": 70,
          "abbr": "BLU"
        },
        {
          "name": "Samurai",
          "level": 50,
          "abbr": "SAM"
        },
        {
          "name": "Paladin",
          "level": 31,
          "abbr": "PLD"
        },
        {
          "name": "Pugilist",
          "level": 21,
          "abbr": "PGL"
        },
        {
          "name": "Marauder",
          "level": 11,
          "abbr": "MRD"
        },
        {
          "name": "Dark Knight",
          "level": 0,
          "abbr": "DRK"
        },
        {
          "name": "Machinist",
          "level": 0,
          "abbr": "MCH"
        }
      ],
      "crafters": [
        {
          "name": "Carpenter",
          "level": 100,
          "abbr": "CRP"
        },
        {
          "name": "Blacksmith",
          "level": 100,
          "abbr": "BSM"
        },
        {
          "name": "Armorer",
          "level": 100,
          "abbr": "ARM"
        },
        {
          "name": "Goldsmith",
          "level": 100,
          "abbr": "GSM"
        },
        {
          "name": "Leatherworker",
          "level": 100,
          "abbr": "LTW"
        },
        {
          "name": "Weaver",
          "level": 100,
          "abbr": "WVR"
        },
        {
          "name": "Alchemist",
          "level": 100,
          "abbr": "ALC"
        },
        {
          "name": "Culinarian",
          "level": 100,
          "abbr": "CUL"
        }
      ],
      "gatherers": [
        {
          "name": "Miner",
          "level": 100,
          "abbr": "MIN"
        },
        {
          "name": "Botanist",
          "level": 100,
          "abbr": "BTN"
        },
        {
          "name": "Fisher",
          "level": 100,
          "abbr": "FSH"
        }
      ],
      "phantom": [
        {
          "name": "Phantom Freelancer",
          "level": 10,
          "abbr": "Freelancer"
        },
        {
          "name": "Phantom Knight",
          "level": 6,
          "abbr": "Knight"
        },
        {
          "name": "Phantom Monk",
          "level": 6,
          "abbr": "Monk"
        },
        {
          "name": "Phantom Cannoneer",
          "level": 6,
          "abbr": "Cannoneer"
        },
        {
          "name": "Phantom Time Mage",
          "level": 5,
          "abbr": "Time Mage"
        },
        {
          "name": "Phantom Oracle",
          "level": 5,
          "abbr": "Oracle"
        },
        {
          "name": "Phantom Chemist",
          "level": 4,
          "abbr": "Chemist"
        },
        {
          "name": "Phantom Bard",
          "level": 4,
          "abbr": "Bard"
        },
        {
          "name": "Phantom Dancer",
          "level": 4,
          "abbr": "Dancer"
        },
        {
          "name": "Phantom Berserker",
          "level": 3,
          "abbr": "Berserker"
        },
        {
          "name": "Phantom Geomancer",
          "level": 3,
          "abbr": "Geomancer"
        },
        {
          "name": "Phantom Thief",
          "level": 1,
          "abbr": "Thief"
        },
        {
          "name": "Phantom Ranger",
          "level": 1,
          "abbr": "Ranger"
        },
        {
          "name": "Phantom Mystic Knight",
          "level": 1,
          "abbr": "Mystic Knight"
        },
        {
          "name": "Phantom Gladiator",
          "level": 1,
          "abbr": "Gladiator"
        }
      ]
    },
    "lastUpdated": "2026-01-16T21:39:19.153Z"
  },
  {
    "id": "24387385",
    "name": "Mira Wa'neko",
    "world": "Zodiark [Light]",
    "image": "https://img2.finalfantasyxiv.com/f/e5de5126497a6bf816908d12fdb2e908_c274370774c6bc3483cc8740805f41bcfl0.jpg?1768583610",
    "jobs": {
      "combat": [
        {
          "name": "White Mage",
          "level": 100,
          "abbr": "WHM"
        },
        {
          "name": "Pictomancer",
          "level": 80,
          "abbr": "PCT"
        },
        {
          "name": "Dancer",
          "level": 60,
          "abbr": "DNC"
        },
        {
          "name": "Gladiator",
          "level": 0,
          "abbr": "GLA"
        },
        {
          "name": "Marauder",
          "level": 0,
          "abbr": "MRD"
        },
        {
          "name": "Dark Knight",
          "level": 0,
          "abbr": "DRK"
        },
        {
          "name": "Gunbreaker",
          "level": 0,
          "abbr": "GNB"
        },
        {
          "name": "Scholar",
          "level": 0,
          "abbr": "SCH"
        },
        {
          "name": "Astrologian",
          "level": 0,
          "abbr": "AST"
        },
        {
          "name": "Sage",
          "level": 0,
          "abbr": "SGE"
        },
        {
          "name": "Pugilist",
          "level": 0,
          "abbr": "PGL"
        },
        {
          "name": "Lancer",
          "level": 0,
          "abbr": "LNC"
        },
        {
          "name": "Rogue",
          "level": 0,
          "abbr": "ROG"
        },
        {
          "name": "Samurai",
          "level": 0,
          "abbr": "SAM"
        },
        {
          "name": "Reaper",
          "level": 0,
          "abbr": "RPR"
        },
        {
          "name": "Viper",
          "level": 0,
          "abbr": "VPR"
        },
        {
          "name": "Archer",
          "level": 0,
          "abbr": "ARC"
        },
        {
          "name": "Machinist",
          "level": 0,
          "abbr": "MCH"
        },
        {
          "name": "Thaumaturge",
          "level": 0,
          "abbr": "THM"
        },
        {
          "name": "Arcanist",
          "level": 0,
          "abbr": "ACN"
        },
        {
          "name": "Red Mage",
          "level": 0,
          "abbr": "RDM"
        },
        {
          "name": "Blue Mage",
          "level": 0,
          "abbr": "BLU"
        }
      ],
      "crafters": [
        {
          "name": "Culinarian",
          "level": 100,
          "abbr": "CUL"
        },
        {
          "name": "Armorer",
          "level": 83,
          "abbr": "ARM"
        },
        {
          "name": "Blacksmith",
          "level": 51,
          "abbr": "BSM"
        },
        {
          "name": "Leatherworker",
          "level": 51,
          "abbr": "LTW"
        },
        {
          "name": "Carpenter",
          "level": 45,
          "abbr": "CRP"
        },
        {
          "name": "Goldsmith",
          "level": 41,
          "abbr": "GSM"
        },
        {
          "name": "Alchemist",
          "level": 39,
          "abbr": "ALC"
        },
        {
          "name": "Weaver",
          "level": 33,
          "abbr": "WVR"
        }
      ],
      "gatherers": [
        {
          "name": "Miner",
          "level": 100,
          "abbr": "MIN"
        },
        {
          "name": "Botanist",
          "level": 100,
          "abbr": "BTN"
        },
        {
          "name": "Fisher",
          "level": 0,
          "abbr": "FSH"
        }
      ],
      "phantom": [
        {
          "name": "Phantom Bard",
          "level": 2,
          "abbr": "Bard"
        },
        {
          "name": "Phantom Knight",
          "level": 1,
          "abbr": "Knight"
        },
        {
          "name": "Phantom Monk",
          "level": 1,
          "abbr": "Monk"
        },
        {
          "name": "Phantom Freelancer",
          "level": 1,
          "abbr": "Freelancer"
        }
      ]
    },
    "lastUpdated": "2026-01-16T21:39:22.425Z"
  }
];

export default characterData;
