// Auto-generated by update-characters.js
// Last updated: 2026-01-18T06:06:53.195Z

const characterData = [
  {
    "id": "9932674",
    "name": "Cereal Knight",
    "world": "Zodiark [Light]",
    "image": "https://img2.finalfantasyxiv.com/f/7f794065dbcb925425ffc7ef849ead6b_c274370774c6bc3483cc8740805f41bcfl0.jpg?1768603891",
    "jobs": {
      "combat": [
        {
          "name": "Paladin",
          "level": 100,
          "abbr": "PLD"
        },
        {
          "name": "Dark Knight",
          "level": 100,
          "abbr": "DRK"
        },
        {
          "name": "White Mage",
          "level": 100,
          "abbr": "WHM"
        },
        {
          "name": "Scholar",
          "level": 100,
          "abbr": "SCH"
        },
        {
          "name": "Monk",
          "level": 100,
          "abbr": "MNK"
        },
        {
          "name": "Reaper",
          "level": 100,
          "abbr": "RPR"
        },
        {
          "name": "Viper",
          "level": 100,
          "abbr": "VPR"
        },
        {
          "name": "Summoner",
          "level": 100,
          "abbr": "SMN"
        },
        {
          "name": "Pictomancer",
          "level": 100,
          "abbr": "PCT"
        },
        {
          "name": "Warrior",
          "level": 93,
          "abbr": "WAR"
        },
        {
          "name": "Dragoon",
          "level": 93,
          "abbr": "DRG"
        },
        {
          "name": "Ninja",
          "level": 91,
          "abbr": "NIN"
        },
        {
          "name": "Samurai",
          "level": 91,
          "abbr": "SAM"
        },
        {
          "name": "Gunbreaker",
          "level": 90,
          "abbr": "GNB"
        },
        {
          "name": "Sage",
          "level": 90,
          "abbr": "SGE"
        },
        {
          "name": "Blue Mage",
          "level": 80,
          "abbr": "BLU"
        },
        {
          "name": "Astrologian",
          "level": 74,
          "abbr": "AST"
        },
        {
          "name": "Bard",
          "level": 70,
          "abbr": "BRD"
        },
        {
          "name": "Machinist",
          "level": 70,
          "abbr": "MCH"
        },
        {
          "name": "Dancer",
          "level": 70,
          "abbr": "DNC"
        },
        {
          "name": "Black Mage",
          "level": 66,
          "abbr": "BLM"
        },
        {
          "name": "Red Mage",
          "level": 66,
          "abbr": "RDM"
        }
      ],
      "crafters": [
        {
          "name": "Carpenter",
          "level": 100,
          "abbr": "CRP"
        },
        {
          "name": "Blacksmith",
          "level": 100,
          "abbr": "BSM"
        },
        {
          "name": "Armorer",
          "level": 100,
          "abbr": "ARM"
        },
        {
          "name": "Goldsmith",
          "level": 100,
          "abbr": "GSM"
        },
        {
          "name": "Leatherworker",
          "level": 100,
          "abbr": "LTW"
        },
        {
          "name": "Weaver",
          "level": 100,
          "abbr": "WVR"
        },
        {
          "name": "Alchemist",
          "level": 100,
          "abbr": "ALC"
        },
        {
          "name": "Culinarian",
          "level": 100,
          "abbr": "CUL"
        }
      ],
      "gatherers": [
        {
          "name": "Miner",
          "level": 100,
          "abbr": "MIN"
        },
        {
          "name": "Botanist",
          "level": 100,
          "abbr": "BTN"
        },
        {
          "name": "Fisher",
          "level": 100,
          "abbr": "FSH"
        }
      ],
      "phantom": [
        {
          "name": "Phantom Knight",
          "level": 6,
          "abbr": "Knight"
        },
        {
          "name": "Phantom Oracle",
          "level": 5,
          "abbr": "Oracle"
        },
        {
          "name": "Phantom Freelancer",
          "level": 3,
          "abbr": "Freelancer"
        },
        {
          "name": "Phantom Berserker",
          "level": 2,
          "abbr": "Berserker"
        },
        {
          "name": "Phantom Monk",
          "level": 1,
          "abbr": "Monk"
        },
        {
          "name": "Phantom Ranger",
          "level": 1,
          "abbr": "Ranger"
        },
        {
          "name": "Phantom Time Mage",
          "level": 1,
          "abbr": "Time Mage"
        },
        {
          "name": "Phantom Chemist",
          "level": 1,
          "abbr": "Chemist"
        },
        {
          "name": "Phantom Bard",
          "level": 1,
          "abbr": "Bard"
        },
        {
          "name": "Phantom Cannoneer",
          "level": 1,
          "abbr": "Cannoneer"
        }
      ]
    },
    "achievements": null,
    "lastUpdated": "2026-01-18T06:06:51.193Z"
  }
];

export default characterData;
